sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t olavokruel/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true olavokruel/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-507590172939"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"