sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t olavokruel/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true olavokruel/docker-react npm run test
